Controllers/CaptainController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RestoApp.Models;
using RestoApp.Models.ViewModels;
using RestoApp.Services;

namespace RestoApp.Controllers
{
    [Authorize(Policy = "Permission_Captain")]
    public class CaptainController : Controller
    {
        private readonly CaptainService menuService;

        public CaptainController(CaptainService menuService)
        {
            this.menuService = menuService;
        }
        public async Task<IActionResult> Order(string table)
        {
            if (!string.IsNullOrEmpty(table))
            {
                var menus = await menuService.GetMenusAsync();
                return View(menus);
            }
            else
            {
                return View("Tables");
            }
        }
        public async Task<IActionResult> Tables()
        {
            var tables = await menuService.GetTablesAsync();
            return View(tables);
        }
        public async Task<IActionResult> GetHallTablesById(string tableId)
        {
            var result = await menuService.GetHallTableByIdAsync(tableId);
            return Json(result);
        }
        public async Task<IActionResult> GetPreviousOrders(int tableId)
        {
            var result = await menuService.GetPreviousOrdersAsync(tableId);
            return Json(result);
        }
        public async Task<IActionResult> AddOrders(OrderMasterViewModel order)
        {
            APIResponseEntity _response = new APIResponseEntity();
            if (ModelState.IsValid)
            {
                _response = await menuService.AddOrdersAsync(order);
            }
            return Json(_response);
        }
        public async Task<IActionResult> OrderBill(int tableId)
        {
            var result = await menuService.OrderBillAsync(tableId);
            return Json(result);
        }
        public async Task<IActionResult> DeletePrevOrderItem(long DetailsId)
        {
            var result = await menuService.DeletePrevOrderItemAsync(DetailsId);
            return Json(result);
        }
        public async Task<IActionResult> UpdatePrevOrderItem(long detailsId, int quantity, string size)
        {
            var result = await menuService.UpdatePrevOrderItemAsync(detailsId, quantity, size);
            return Json(result);
        }
    }
}

Views/Captain/Order.cshtml
@model APIResponseEntity
<style>
    .main {
        padding: 0 !important;
    }
</style>

<div class="main-container d-flex">
    <div class="container position-relative p-3">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">

            @{
                int i = 0;
            }
            @foreach (var c in Model.data)
            {
                if (i == 0)
                {
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="pills_@c.CategoryId" data-bs-toggle="pill" data-bs-target="#tab_@c.CategoryId" type="button" role="tab" aria-controls="tab_@c.CategoryId" aria-selected="true">
                            @c.CategoryName
                        </button>
                    </li>
                }
                else
                {
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills_@c.CategoryId" data-bs-toggle="pill" data-bs-target="#tab_@c.CategoryId" type="button" role="tab" aria-controls="tab_@c.CategoryId" aria-selected="true">
                            @c.CategoryName
                        </button>
                    </li>
                }
                i++;
            }
        </ul>
        <div class="tab-content" id="pills-tabContent">
            @{
                i = 0;
                string activeClass = "active";
            }
            @foreach (var c in Model.data)
            {
                if (i > 0)
                {
                    activeClass = "";
                }
                i++;
                <div class="tab-pane fade show @activeClass" id="tab_@c.CategoryId" role="tabpanel" aria-labelledby="pills_@c.CategoryId" tabindex="0">
                    <div class="menu-container">
                        @foreach (var menu in c.Menus)
                        {
                            <div class="card menu-card" onclick="addOrders('@menu.MenuId','@menu.Name')">
                                <div class="image_container">
                                    <img src="/menuImages/@menu.ImagePath" alt="@menu.ImagePath" class="w-75 h-75" />
                                </div>
                                <div class="title">
                                    <span>@menu.Name</span>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            }
        </div>
        <div class="mob-order">
            <span><i class="bi bi-bag-plus-fill"></i></span>
            <span class="position-absolute top-0 start-85 translate-middle badge rounded-pill bg-danger fs-6 order-count d-none">
            </span>
        </div>
    </div>
    <div class="order-container">
        <div class="p-3 border-bottom">
            <div>
                <h3>Order ID  - <span class="preOrderId"></span></h3>
                <input type="hidden" id="orderId" />
            </div>
            <div class="d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center">
                    <i class="bi bi-dot fs-3"></i>
                    <h6 class="order-hall m-0">H1</h6>
                </div>
                <div class="d-flex align-items-center pe-2">
                    <span>Dine-in</span>
                    <i class="bi bi-dot fs-3"></i>
                    <h6 class="order-table m-0">T1</h6>
                </div>
            </div>
        </div>
        <div class="accordion">
        </div>
        <div class="position-absolute bottom-0 p-2 ps-3 pe-3 w-100 d-flex gap-2">
            <button class="btn w-100 justify-content-center btnUserBill" disabled>
                <span><i class="bi bi-receipt-cutoff"></i></span>
                <span>Bill</span>
            </button>
            <button class="btn btn-success w-100 justify-content-center btnUserOrder" disabled>
                <span><i class="bi bi-send-fill"></i></span>
                <span>Order</span>
            </button>
        </div>
    </div>
</div>
<script src="~/js/order.js"></script>

Views/Captain/Tables.cshtml
@model APIResponseEntity

<div class="main-container d-flex p-3">
    <div class="container">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            @{
                int i = 0;
            }
            @foreach (var hall in Model.data)
            {
                if (i == 0)
                {
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="pills_@hall.HallId" data-bs-toggle="pill" data-bs-target="#tab_@hall.HallId" type="button" role="tab" aria-controls="tab_@hall.HallId" aria-selected="true">
                            @hall.HallName
                        </button>
                    </li>
                }
                else
                {
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills_@hall.HallId" data-bs-toggle="pill" data-bs-target="#tab_@hall.HallId" type="button" role="tab" aria-controls="tab_@hall.HallId" aria-selected="true">
                            @hall.HallName
                        </button>
                    </li>
                }
                i++;
            }
        </ul>
        <div class="tab-content" id="pills-tabContent">
            @{
                i = 0;
                string activeClass = "active";
            }
            @foreach (var hall in Model.data)
            {
                if (i > 0)
                {
                    activeClass = "";
                }
                i++;
                <div class="tab-pane fade show @activeClass" id="tab_@hall.HallId" role="tabpanel" aria-labelledby="pills_@hall.HallId" tabindex="0">
                    <div class="menu-container justify-content-start">
                        @foreach (var table in hall.tables)
                        {
                            string occupiedClass = "table-unoccupied";
                            if (table.IsOccupied)
                            {
                                occupiedClass = "table-occupied";
                            }
                            <a href="@Url.Action("Order", "Captain", new { table=table.Id })" class="text-decoration-none @occupiedClass">
                                <div class="card menu-card bg-transparent border-0 w-auto">
                                    <div class="image_container w-auto">
                                        <img src="/menuImages/DinningSmallTable.svg" alt="tables" class="h-100" />
                                    </div>
                                    <div class="title">
                                        <span>@table.Name</span>
                                    </div>
                                </div>
                            </a>
                        }
                    </div>
                </div>
            }
        </div>
        
    </div>
</div>